version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
  mysql:
    build: ./mysql
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test
    - MYSQL_DATABASE=todolist
#  kafka:
#    image: spotify/kafka
#    ports:
#      - "2181:2181"
#      - "9092:9092"
#      - "7209:7209"
#    environment:
#      JMX_PORT: 7209
#      ADVERTISED_HOST: 192.168.99.100
#      ADVERTISED_PORT: 9092
#    networks:
#      - prodnetwork
#  kafka-manager:
#    image: sheepkiller/kafka-manager
#    ports:
#      - "29000:9000"
#    environment:
#      ZK_HOSTS: zk:2181
#    networks:
#      - prodnetwork
#    links:
#      - kafka:zk
#    depends_on:
#      - kafka
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    build: ./kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    links:
#      - zookeeper
#  kafka-manager:
#    image: sheepkiller/kafka-manager
#    ports:
#      - "29000:9000"
#    environment:
#      ZK_HOSTS: zookeeper:2181
#    links:
#      - zookeeper
#    depends_on:
#      - kafka