server:
  port: 8092
logging.level.org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: test
      password: test
      username: test
  cloud:
    stream:
#      kafka:
#        binder:
#          brokers: 192.168.99.100:9092
#          zkNodes: 192.168.99.100:2181
      bindings:
        input-res-created:
          destination: command.created
          group:  todo.create.response
          binder: rabbit1
        output-req-create:
          destination: command.create
          content-type: application/json
          binder: rabbit1
          producer:
            requiredGroups: todo.create
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.99.100
                port: 5672
                username: test
                password: test
                virtual-host: /test
#        kafka1:
#         type: kafka
#         environment:
#           spring:
#             cloud:
#               stream:
#                kafka:
#                  binder:
#                    brokers: 192.168.99.100:9092
#                    zkNodes: 192.168.99.100:2181


