server:
  port: 8094

mysql:
  server: 192.168.99.100
  port: 3306
spring:
  datasource:
      url: jdbc:mysql://${mysql.server}:${mysql.port}/user_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: test
      password: test
      driver-class-name: com.mysql.jdbc.Driver
      test-on-borrow: true
      test-while-idle: true
      validation-query: select 1
      max-active: 10
      max-idle: 5
      min-idle: 1
      initial-size: 5
      time-between-eviction-runs-millis: 5000
      min-evictable-idle-time-millis: 60000
  cloud:
    stream:
#      kafka:
#        binder:
#          brokers: 192.168.99.100:9092
#          zkNodes: 192.168.99.100:2181
      bindings:
        input-todo-command:
          destination: input.command
          group: todo.command
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.99.100
                port: 5672
                username: test
                password: test
                virtual-host: /test
#        kafka1:
#         type: kafka
#         environment:
#           spring:
#             cloud:
#               stream:
#                kafka:
#                  binder:
#                    brokers: 192.168.99.100:9092
#                    zkNodes: 192.168.99.100:2181


