server:
  port: 8093
logging.level.org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
#  data:
#    mongodb:
#      host: 192.168.99.100
#      port: 27017
#      database: event-sourcing
  cloud:
    stream:
#      kafka:
#        binder:
#          brokers: 192.168.99.100:9092
#          zkNodes: 192.168.99.100:2181
      bindings:
        input-event:
          destination: event.notify
          group: input.event.driven
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.99.100
                port: 5672
                username: test
                password: test
                virtual-host: /test
#        kafka1:
#         type: kafka
#         environment:
#           spring:
#             cloud:
#               stream:
#                kafka:
#                  binder:
#                    brokers: 192.168.99.100:9092
#                    zkNodes: 192.168.99.100:2181


